In [2]:
#
import pandas as pd
from pandas import Series, DataFrame
import numpy as np
from numpy import nan as NA
import sys

In [3]:
#
import matplotlib.pylab as plt
from numpy.random import randn
%matplotlib inline

# Chapter 12: Advanced NumPy

Run next cell to create arr1 and arr2

In [4]:
#
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

Concatenate arr1 and arr2 in axis 1

In [5]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

Run next cell to create arr

In [6]:
#
arr = randn(5, 2)

Split arr to three parts along the axis 0

In [7]:
first, second, third = np.split(arr, [1, 3])
print(first)
print("===")
print(second)
print("===")
print(third)

[[-1.18286153 -0.24436626]]
===
[[ 0.26508513 -0.87744985]
 [-1.51718889  0.10001343]]
===
[[ 1.58827231 -0.26523704]
 [ 1.45146498 -0.39248213]]


Convert array([0, 1, 2]) to array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [8]:
#
arr = np.arange(3)

In [9]:
np.repeat(arr, 3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

Convert array([0, 1, 2]) to array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [10]:
np.repeat(arr, [2, 3, 4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

Run next cell to create array a

In [12]:
#
a = randn(2, 2)

Create a new array of [a, a, a; a, a, a] from a

In [13]:
np.tile(a, (2, 3))

array([[-0.28309829,  0.44505617, -0.28309829,  0.44505617, -0.28309829,
         0.44505617],
       [-1.65979155, -0.50497249, -1.65979155, -0.50497249, -1.65979155,
        -0.50497249],
       [-0.28309829,  0.44505617, -0.28309829,  0.44505617, -0.28309829,
         0.44505617],
       [-1.65979155, -0.50497249, -1.65979155, -0.50497249, -1.65979155,
        -0.50497249]])

Run next cell to create an array arr

In [14]:
#
arr = np.arange(10)*100
arr

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

Now, using one line code to replace arr[7] as 40, arr[1] as 41, arr[2] as 42, and arr[6] as 43

In [15]:
arr.put([7, 1, 2, 6], [40, 41, 42, 43])
arr

array([  0,  41,  42, 300, 400, 500,  43,  40, 800, 900])

Run next cell to create arr

In [16]:
#
arr = randn(1000, 50)

Randomize the rows of arr by two ways: fancy indexing and the take method. Compare the performance of these methods by %timeit

In [17]:
inds = np.random.permutation(np.shape(arr)[0])

In [20]:
%timeit arr[inds]

30.1 µs ± 1.23 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [21]:
%timeit arr.take(inds)

1.52 µs ± 139 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Run next cell to create arr

In [22]:
#
arr = randn(4, 3)
arr

array([[-1.04719466, -0.52470784, -1.34088061],
       [-0.27749585,  1.39579886,  0.23457673],
       [ 0.66350709,  0.57351965, -0.94790825],
       [ 0.71288677, -1.5371095 ,  0.86224093]])

2D broadcasting: subtract column mean from each element in arr. Then prove that the the column mean of the result is zero.

In [25]:
c_mean = arr.mean(axis=0)
c_mean

array([ 0.01292584, -0.02312471, -0.2979928 ])

In [26]:
result = arr - c_mean
result.mean(axis=0)

array([0., 0., 0.])

2D broadcasting: subtract row mean from each element in arr. Then prove that the the row mean of the result is zero.

In [27]:
r_mean = arr.mean(axis=1)
r_mean

array([-0.9709277 ,  0.45095991,  0.09637283,  0.01267273])

In [28]:
r_mean = r_mean[:, np.newaxis]
r_mean

array([[-0.9709277 ],
       [ 0.45095991],
       [ 0.09637283],
       [ 0.01267273]])

In [31]:
result = arr - r_mean
result.mean(axis=1)

array([3.70074342e-17, 2.77555756e-17, 0.00000000e+00, 0.00000000e+00])

Run next cell to create arr

In [32]:
#
arr = randn(3, 4, 5)

3D broadcasting: subtract row mean from each element in arr (axis=1). Then prove that the the row mean of the result is zero.

In [33]:
r_mean = arr.mean(axis=1)
r_mean

array([[-1.2399865 , -0.21005721, -0.48026207, -1.26387737, -0.49967925],
       [-0.20203994, -0.02163227,  0.36367493, -0.27096274, -0.28979863],
       [-0.39235805, -0.73188789,  0.05990404, -0.47668095,  0.3352076 ]])

In [34]:
r_mean = r_mean[:, np.newaxis, :]
r_mean.shape

(3, 1, 5)

In [35]:
result = arr-r_mean
result.mean(axis=1)

array([[-1.66533454e-16,  0.00000000e+00,  0.00000000e+00,
        -2.77555756e-17,  2.77555756e-17],
       [ 0.00000000e+00,  0.00000000e+00, -2.77555756e-17,
         5.55111512e-17,  0.00000000e+00],
       [ 1.38777878e-17,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  2.77555756e-17]])

Run next cell to create arr and arr2

In [40]:
#
arr = np.zeros((4, 3))
arr2 = np.array([1, 2, 3, 4])

Set values by broadcasting: set each column of arr as arr2

In [41]:
arr[:] = arr2[:, np.newaxis]
arr

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.]])

Set values by broadcasting: set first row of arr as 10 the the second row as 11

In [42]:
arr[:2, :] = np.array([[10], [11]])
arr

array([[10., 10., 10.],
       [11., 11., 11.],
       [ 3.,  3.,  3.],
       [ 4.,  4.,  4.]])

Run next cell to define a function.

In [43]:
# 
def add_elements(x, y):
    return x + y

Define a new numpy ufunc 'add_them' to apply add_elements on two arrays element-wisely.

In [45]:
add_them = np.frompyfunc(add_elements, 2, 1)

In [46]:
add_them(np.arange(8), np.arange(8))

array([0, 2, 4, 6, 8, 10, 12, 14], dtype=object)

Repeat last question and make sure the output of the new function has a data type of np.float64

In [47]:
add_them = np.vectorize(add_elements, otypes=[np.float64])
add_them(np.arange(8), np.arange(8))

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

Run next cell to define arr.

In [48]:
#
arr = randn(10000)

Compare the time cost of user-defined ufunc add_them(arr, arr) and the built-in numpy function np.add(arr, arr)

In [49]:
%timeit add_them(arr, arr)

1.57 ms ± 182 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [50]:
%timeit np.add(arr, arr)

3.33 µs ± 188 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Run next cell to create "name"

In [56]:
#
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])
name = np.array([last_name, first_name])
name

array([['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'],
       ['Bob', 'Jane', 'Steve', 'Bill', 'Barbara']], dtype='<U7')

Sort name. Use last name as the primary key and first name as the secondary key.

In [57]:
sorter = np.lexsort((name[1], name[0]))

In [58]:
name[:, sorter]

array([['Arnold', 'Arnold', 'Jones', 'Jones', 'Walters'],
       ['Jane', 'Steve', 'Bill', 'Bob', 'Barbara']], dtype='<U7')

Run next cell to create a sorted array "arr"

In [64]:
arr = np.sort(np.array([0, 1, 7, 12, 15]))
arr

array([ 0,  1,  7, 12, 15])

Now insert [0, 8, 11, 16] into arr and keep the ascending order

In [67]:
value = np.array([0, 8, 11, 16])
pos = np.searchsorted(arr, value)

In [68]:
pos

array([0, 3, 3, 5])

In [69]:
np.insert(arr, pos, value)

array([ 0,  0,  1,  7,  8, 11, 12, 15, 16])