In [1]:
#
import pandas as pd
from pandas import Series, DataFrame
import numpy as np
from numpy import nan as NA
import sys

In [2]:
#
import matplotlib.pylab as plt
from numpy.random import randn
%matplotlib inline

# Chapter 12: Advanced NumPy

Run next cell to create arr1 and arr2

In [3]:
#
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

Concatenate arr1 and arr2 in axis 1

In [4]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

Run next cell to create arr

In [5]:
#
arr = randn(5, 2)

Split arr to three parts along the axis 0

In [6]:
first, second, third = np.split(arr, [1, 3])
print(first)
print("===")
print(second)
print("===")
print(third)

[[-0.34767245 -0.39894751]]
===
[[-1.63815218 -0.79970512]
 [-1.24955653  0.80095886]]
===
[[ 2.15927307 -0.30645637]
 [-0.11025443 -0.49557355]]


Convert array([0, 1, 2]) to array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [7]:
#
arr = np.arange(3)

In [8]:
np.repeat(arr, 3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

Convert array([0, 1, 2]) to array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [9]:
np.repeat(arr, [2, 3, 4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

Run next cell to create array a

In [10]:
#
a = randn(2, 2)

Create a new array of [a, a, a; a, a, a] from a

In [11]:
np.tile(a, (2, 3))

array([[ 0.70325707, -0.11485124,  0.70325707, -0.11485124,  0.70325707,
        -0.11485124],
       [ 0.61456476, -0.49169892,  0.61456476, -0.49169892,  0.61456476,
        -0.49169892],
       [ 0.70325707, -0.11485124,  0.70325707, -0.11485124,  0.70325707,
        -0.11485124],
       [ 0.61456476, -0.49169892,  0.61456476, -0.49169892,  0.61456476,
        -0.49169892]])

Run next cell to create an array arr

In [12]:
#
arr = np.arange(10)*100
arr

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

Now, using one line code to replace arr[7] as 40, arr[1] as 41, arr[2] as 42, and arr[6] as 43

In [13]:
arr.put([7, 1, 2, 6], [40, 41, 42, 43])
arr

array([  0,  41,  42, 300, 400, 500,  43,  40, 800, 900])

Run next cell to create arr

In [14]:
#
arr = randn(1000, 50)

Randomize the rows of arr by two ways: fancy indexing and the take method. Compare the performance of these methods by %timeit

In [15]:
inds = np.random.permutation(np.shape(arr)[0])

In [16]:
%timeit arr[inds]

30.8 µs ± 2.58 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [17]:
%timeit arr.take(inds)

1.52 µs ± 106 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Run next cell to create arr

In [18]:
#
arr = randn(4, 3)
arr

array([[ 0.4266484 ,  0.30281026, -1.8735606 ],
       [-0.15574002,  1.1022017 ,  0.46882173],
       [-0.44954005,  0.2159974 ,  0.2313078 ],
       [-1.36303376,  0.14178352,  0.98843823]])

2D broadcasting: subtract column mean from each element in arr. Then prove that the the column mean of the result is zero.

In [19]:
c_mean = arr.mean(axis=0)
c_mean

array([-0.38541636,  0.44069822, -0.04624821])

In [20]:
result = arr - c_mean
result.mean(axis=0)

array([-2.77555756e-17,  0.00000000e+00,  5.55111512e-17])

2D broadcasting: subtract row mean from each element in arr. Then prove that the the row mean of the result is zero.

In [21]:
r_mean = arr.mean(axis=1)
r_mean

array([-0.38136731,  0.47176114, -0.00074495, -0.077604  ])

In [22]:
r_mean = r_mean[:, np.newaxis]
r_mean

array([[-0.38136731],
       [ 0.47176114],
       [-0.00074495],
       [-0.077604  ]])

In [23]:
result = arr - r_mean
result.mean(axis=1)

array([ 7.40148683e-17,  3.70074342e-17, -9.25185854e-18,  0.00000000e+00])

Run next cell to create arr

In [24]:
#
arr = randn(3, 4, 5)

3D broadcasting: subtract row mean from each element in arr (axis=1). Then prove that the the row mean of the result is zero.

In [25]:
r_mean = arr.mean(axis=1)
r_mean

array([[-0.63721297,  0.45157929,  0.06336402, -0.67470079, -0.49431028],
       [ 0.27881178, -0.05746635, -0.75232705, -0.57383768, -0.32980978],
       [-0.34749951,  0.7996496 , -0.81662022, -0.06428601, -0.03518981]])

In [26]:
r_mean = r_mean[:, np.newaxis, :]
r_mean.shape

(3, 1, 5)

In [27]:
result = arr-r_mean
result.mean(axis=1)

array([[-8.32667268e-17,  0.00000000e+00, -2.77555756e-17,
        -5.55111512e-17, -2.77555756e-17],
       [ 0.00000000e+00,  0.00000000e+00, -4.16333634e-17,
         0.00000000e+00, -4.16333634e-17],
       [-2.77555756e-17,  2.77555756e-17,  0.00000000e+00,
        -5.55111512e-17,  0.00000000e+00]])

Run next cell to create arr and arr2

In [28]:
#
arr = np.zeros((4, 3))
arr2 = np.array([1, 2, 3, 4])

Set values by broadcasting: set each column of arr as arr2

In [29]:
arr[:] = arr2[:, np.newaxis]
arr

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.]])

Set values by broadcasting: set first row of arr as 10 the the second row as 11

In [30]:
arr[:2, :] = np.array([[10], [11]])
arr

array([[10., 10., 10.],
       [11., 11., 11.],
       [ 3.,  3.,  3.],
       [ 4.,  4.,  4.]])

Run next cell to define a function.

In [31]:
# 
def add_elements(x, y):
    return x + y

Define a new numpy ufunc 'add_them' to apply add_elements on two arrays element-wisely.

In [32]:
add_them = np.frompyfunc(add_elements, 2, 1)

In [33]:
add_them(np.arange(8), np.arange(8))

array([0, 2, 4, 6, 8, 10, 12, 14], dtype=object)

Repeat last question and make sure the output of the new function has a data type of np.float64

In [34]:
add_them = np.vectorize(add_elements, otypes=[np.float64])
add_them(np.arange(8), np.arange(8))

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

Run next cell to define arr.

In [35]:
#
arr = randn(10000)

Compare the time cost of user-defined ufunc add_them(arr, arr) and the built-in numpy function np.add(arr, arr)

In [36]:
%timeit add_them(arr, arr)

2.05 ms ± 922 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [37]:
%timeit np.add(arr, arr)

3.53 µs ± 985 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Run next cell to create "name"

In [38]:
#
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])
name = np.array([last_name, first_name])
name

array([['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'],
       ['Bob', 'Jane', 'Steve', 'Bill', 'Barbara']], dtype='<U7')

Sort name. Use last name as the primary key and first name as the secondary key.

In [39]:
sorter = np.lexsort((name[1], name[0]))

In [40]:
name[:, sorter]

array([['Arnold', 'Arnold', 'Jones', 'Jones', 'Walters'],
       ['Jane', 'Steve', 'Bill', 'Bob', 'Barbara']], dtype='<U7')

Run next cell to create a sorted array "arr"

In [41]:
arr = np.sort(np.array([0, 1, 7, 12, 15]))
arr

array([ 0,  1,  7, 12, 15])

Now insert [0, 8, 11, 16] into arr and keep the ascending order

In [42]:
value = np.array([0, 8, 11, 16])
pos = np.searchsorted(arr, value)

In [43]:
pos

array([0, 3, 3, 5])

In [44]:
np.insert(arr, pos, value)

array([ 0,  0,  1,  7,  8, 11, 12, 15, 16])